package com.example.attendance2;

import android.os.Bundle;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.Toast;
import androidx.appcompat.app.AppCompatActivity;

import com.example.attendance2.Model.Student;
import com.google.firebase.firestore.FirebaseFirestore;

public class AddStudent extends AppCompatActivity {

    private EditText studentName, studentRollNo, studentClass, studentEmail;
    private Button submitButton;
    private FirebaseFirestore db;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_add_student);

        studentName = findViewById(R.id.studentName);
        studentRollNo = findViewById(R.id.studentRollNo);
        studentClass = findViewById(R.id.studentClass);
        studentEmail = findViewById(R.id.studentEmail);
        submitButton = findViewById(R.id.submitStudentButton);

        // Initialize Firestore
        db = FirebaseFirestore.getInstance();

        submitButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                // Get values from input fields
                String name = studentName.getText().toString().trim();
                String rollNo = studentRollNo.getText().toString().trim();
                String studentClassValue = studentClass.getText().toString().trim();
                String email = studentEmail.getText().toString().trim();

                // Validate input
                if (name.isEmpty() || rollNo.isEmpty() || studentClassValue.isEmpty() || email.isEmpty()) {
                    Toast.makeText(AddStudent.this, "Please fill all fields", Toast.LENGTH_SHORT).show();
                    return;
                }

                // Create student object (id will be generated by Firestore)
                Student student = new Student(null, name, rollNo, studentClassValue, email);

                // Add student to Firestore
                db.collection("students")
                        .add(student)
                        .addOnSuccessListener(documentReference -> {
                            // Get the generated document ID from Firestore
                            String studentId = documentReference.getId();
                            student.setId(studentId);
                            documentReference.update("id", studentId);

                            Toast.makeText(AddStudent.this, "Student " + name + " added", Toast.LENGTH_SHORT).show();
                            finish();
                        })
                        .addOnFailureListener(e -> {
                            // Handle failure
                            Toast.makeText(AddStudent.this, "Error: " + e.getMessage(), Toast.LENGTH_SHORT).show();
                        });
            }
        });

    }
}
